services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: foyer
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2

  app:
    depends_on:
      - mysqldb
    image: melekmejri/tp-foyer:latest  # Corrected image name
    build: .  # Ensure Dockerfile is in this directory
    restart: on-failure
    ports:
      - "8089:8089"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      mynetwork:
        ipv4_address: 172.18.0.3

volumes:
  db:

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
